name: Starter_CI

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  # schedule:
  #   - cron: '0/10 * * * *'
  schedule:
    - cron: '*/5 * * * *'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-with-stable-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run collection GeoIP_C50511536 Get basic information
        run: newman run postman/collections/C50511536.json -e postman/environments/PROD.json

      - name: Run collection GeoIP_C50511609 Block list control
        run: newman run postman/collections/C50511609.json -e postman/environments/PROD.json

  run-with-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
      - name: Run collection GeoIP_C50511536 Get basic information
        run: |
          postman collection run "39045251-25ba4f09-f1c7-43b0-85c0-58448f0d48ef" -e "22979062-2035ed95-703b-4efb-9d42-86383e269aa2"       

      - name: Run collection GeoIP_C50511609 Block list control
        run: |
          postman collection run "39045251-25ba4f09-f1c7-43b0-85c0-58448f0d48ef" -e "22979062-2035ed95-703b-4efb-9d42-86383e269aa2"
